# Generated by Django 4.0.3 on 2022-03-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name_plural': 'Dépenses'},
        ),
    ]
