# Generated by Django 4.0.3 on 2022-03-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depenses', '0002_alter_category_options_alter_expenses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.TextField(),
        ),
    ]
