# Generated by Django 3.1.2 on 2022-03-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depenses', '0004_auto_20220331_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total',
        ),
    ]
